import { metric } from './metricAssessment.js'
import { accelerationLabel } from './portfolioAcceleration.js'
import { shortTermVerdict } from './portfolioShortTermView.js'

const finite = (value) => value !== null && value !== '' && typeof value !== 'boolean' && Number.isFinite(Number(value))
const ratio = (value) => finite(value) ? Number(value).toFixed(2) : 'Insufficient'
const percent = (value, digits = 1) => finite(value) ? `${Number(value).toFixed(digits)}%` : 'Insufficient'
const signedPercent = (value, digits = 1) => finite(value) ? `${Number(value) >= 0 ? '+' : '−'}${Math.abs(Number(value)).toFixed(digits)}%` : 'Insufficient'
const count = (value) => finite(value) ? Math.round(Number(value)).toLocaleString() : 'Insufficient'
const duration = (value) => {
  if (!finite(value)) return 'Insufficient'
  if (Number(value) < 60) return `${Math.round(Number(value))}d`
  const months = Number(value) / 30.44
  return months < 18 ? `${months.toFixed(1)}mo` : `${(Number(value) / 365.25).toFixed(1)}y`
}
const median = (values = []) => {
  const ordered = values.filter(finite).map(Number).sort((left, right) => left - right)
  if (!ordered.length) return null
  const middle = Math.floor(ordered.length / 2)
  return ordered.length % 2 ? ordered[middle] : (ordered[middle - 1] + ordered[middle]) / 2
}

const TOOLTIP = {
  sharpe: { measures: 'Return above the risk-free rate per unit of total volatility.', better: 'Higher is commonly regarded as better, but the confidence band determines whether the estimate is distinguishable from noise.' },
  sortino: { measures: 'Return above the risk-free rate per unit of downside deviation.', better: 'Higher is commonly regarded as better; it does not measure upside volatility as risk.' },
  calmar: { measures: 'Annualized return divided by the magnitude of maximum drawdown.', better: 'Higher is commonly regarded as better, conditional on a sufficiently long sample.' },
  psr: { measures: 'Probability that the true Sharpe exceeds the selected threshold after skew and kurtosis.', better: 'At least 95% is this dashboard’s positive-evidence threshold.' },
  dsr: { measures: 'Probabilistic Sharpe after accounting for the number and dispersion of tried strategies.', better: 'Higher is stronger; it is unavailable unless the trial registry includes cross-trial Sharpe variance.' },
  mintrl: { measures: 'Number of observations needed for the current Sharpe to reach the selected PSR confidence.', better: 'Fewer required observations is more useful, but a non-positive Sharpe is not estimable.' },
  information: { measures: 'Annualized active return per unit of tracking error against the named benchmark.', better: 'Higher is commonly regarded as better, but only when the benchmark fits the strategy.' },
  tracking: { measures: 'Volatility of portfolio returns relative to the benchmark.', better: 'Neither high nor low is inherently better; compare it with the strategy’s own baseline.' },
  capture: { measures: 'Portfolio participation in benchmark up and down periods.', better: 'Higher up-capture and lower down-capture form favourable asymmetry.' },
  activeShare: { measures: 'Share of current portfolio weights that differs from benchmark constituent weights.', better: 'It is descriptive, not a performance score.' },
  es: { measures: 'Average loss in returns beyond the selected tail percentile.', better: 'Smaller tail losses are generally preferable for the same return objective.' },
  alpha: { measures: 'Intercept after removing the named systematic factor returns.', better: 'Positive alpha with a Newey–West HAC t-statistic above 3 is this dashboard’s evidence hurdle.' },
  breakEven: { measures: 'All-in per-trade cost that reduces average net excess return, and therefore net Sharpe, to zero.', better: 'A larger buffer over realistic costs is generally preferable.' },
  turnover: { measures: 'Half the absolute portfolio weight change at each rebalance; two-way turnover is twice that.', better: 'Lower is not inherently better, but turnover must earn more than its implementation cost.' },
  pbo: { measures: 'Probability that the in-sample-best configuration ranks below the out-of-sample median under CSCV.', better: 'Below 0.5 is the registered robustness convention.' },
  wfe: { measures: 'Out-of-sample annualized performance divided by in-sample annualized performance.', better: 'Above 0.5 is a common robustness convention, not a statistical cutoff.' },
}

function base(input, sample, overrides = {}) {
  return metric({
    category: 'Risk',
    observations: sample?.observations ?? null,
    startDate: sample?.startDate || null,
    endDate: sample?.endDate || null,
    frequency: sample?.frequency || 'daily',
    ...input,
    ...overrides,
  })
}

function missing(name, id, family, category, reason, group, priority = 20, tooltip) {
  return metric({ id, name, family, category, value: null, formattedValue: 'Insufficient', frequency: 'point', insufficientReason: reason, group, priority, tooltip: tooltip || { measures: name } })
}

export function buildPortfolioMetricModel({
  performance = null,
  statistics = null,
  acceleration = null,
  capture = null,
  batting = null,
  underwater = null,
  shortTerm = null,
  risk = null,
  factor = null,
  benchmark = null,
  benchmarkComparisons = null,
  exposure = null,
  execution = null,
  robustness = null,
  regime = null,
  legacyPortfolioScore = null,
} = {}) {
  const sample = statistics?.available ? statistics : {
    observations: performance?.observations ?? statistics?.observations ?? 0,
    startDate: performance?.startDate || null,
    endDate: performance?.endDate || null,
    frequency: 'daily',
  }
  const performanceReason = performance?.reason || statistics?.reason || 'daily portfolio returns are required'
  const standard = []
  const performanceValue = (key) => performance?.available ? performance[key] : null
  const unavailable = !performance?.available ? performanceReason : null
  standard.push(base({ id: 'sharpe', name: 'Sharpe ratio', family: 'return_efficiency', category: 'Return', value: performanceValue('sharpe'), formattedValue: ratio(performanceValue('sharpe')), supportingValue: statistics?.available ? `95% band ${statistics.sharpeConfidence95.map((value) => value.toFixed(2)).join(' to ')}` : undefined, minObservations: 20, insufficientReason: unavailable, group: 'Risk-Adjusted Return', priority: 100, tooltip: TOOLTIP.sharpe }, sample))
  standard.push(base({ id: 'lo_adjusted_sharpe', name: 'Lo-adjusted Sharpe', family: 'return_efficiency', category: 'Statistical', value: statistics?.loAdjustedSharpe, formattedValue: ratio(statistics?.loAdjustedSharpe), supportingValue: statistics?.loFactor?.available ? `η(252) ${statistics.loFactor.value.toFixed(2)} · serial-correlation adjusted` : undefined, minObservations: 253, insufficientReason: statistics?.available && !statistics.loFactor?.available ? statistics.loFactor.reason : statistics?.available ? null : statistics?.reason, group: 'Risk-Adjusted Return', priority: 98, tooltip: { measures: 'Sharpe annualized with Lo’s autocorrelation-aware scaling.', better: 'Compare it with naive Sharpe; a material gap indicates serial dependence.' } }, sample))
  standard.push(base({ id: 'sortino', name: 'Sortino ratio', family: 'return_efficiency', category: 'Return', value: performanceValue('sortino'), formattedValue: ratio(performanceValue('sortino')), minObservations: 20, insufficientReason: unavailable, group: 'Risk-Adjusted Return', priority: 75, tooltip: TOOLTIP.sortino }, sample))
  standard.push(base({ id: 'lo_adjusted_sortino', name: 'Lo-adjusted Sortino', family: 'return_efficiency', category: 'Return', value: statistics?.loAdjustedSortino, formattedValue: ratio(statistics?.loAdjustedSortino), supportingValue: 'Autocorrelation-aware annualization', minObservations: 253, insufficientReason: statistics?.available && !statistics.loFactor?.available ? statistics.loFactor.reason : statistics?.available ? null : statistics?.reason, group: 'Risk-Adjusted Return', priority: 74, tooltip: { measures: 'Sortino ratio using Lo’s serial-correlation-aware annualization factor.' } }, sample))
  standard.push(base({ id: 'naive_volatility', name: 'Volatility (naive √252)', family: 'tail_risk', category: 'Risk', value: statistics?.naiveVolatilityPct, formattedValue: percent(statistics?.naiveVolatilityPct), minObservations: 20, insufficientReason: statistics?.available ? null : statistics?.reason, descriptive: true, group: 'Tail Risk', priority: 63, tooltip: { measures: 'Daily excess-return volatility scaled by √252; shown for convention and comparison.' } }, sample))
  standard.push(base({ id: 'lo_adjusted_volatility', name: 'Volatility (Lo-adjusted)', family: 'tail_risk', category: 'Risk', value: statistics?.loAdjustedVolatilityPct, formattedValue: percent(statistics?.loAdjustedVolatilityPct), minObservations: 253, insufficientReason: statistics?.available && !statistics.loFactor?.available ? statistics.loFactor.reason : statistics?.available ? null : statistics?.reason, descriptive: true, group: 'Tail Risk', priority: 64, tooltip: { measures: 'Daily excess-return volatility scaled with Lo’s autocorrelation adjustment.' } }, sample))
  standard.push(base({ id: 'calmar', name: 'Calmar ratio', family: 'return_efficiency', category: 'Return', value: performanceValue('calmar'), formattedValue: ratio(performanceValue('calmar')), minObservations: 20, insufficientReason: unavailable, group: 'Risk-Adjusted Return', priority: 72, tooltip: TOOLTIP.calmar }, sample))
  standard.push(base({ id: 'annualized_return', name: 'Annualized return', family: 'return_efficiency', category: 'Return', value: performanceValue('annualizedReturn'), formattedValue: signedPercent(performanceValue('annualizedReturn')), minObservations: 20, insufficientReason: unavailable, group: 'Return & Compounding', priority: 68, descriptive: true, tooltip: { measures: 'Compound growth projected to 252 trading days over the displayed sample.' } }, sample))

  const psr = statistics?.psr
  standard.push(base({ id: 'psr', name: 'Probabilistic Sharpe ratio', family: 'statistical_confidence', category: 'Statistical', value: psr?.available ? psr.value : null, formattedValue: psr?.available ? percent(psr.value * 100) : 'Insufficient', minObservations: 20, insufficientReason: psr?.available ? null : psr?.reason || statistics?.reason, group: 'Statistical Confidence', priority: 100, tooltip: TOOLTIP.psr }, sample))
  standard.push(base({ id: 'sharpe_t_stat', name: 'Sharpe t-statistic', family: 'statistical_confidence', category: 'Statistical', value: statistics?.sharpeTStatistic, formattedValue: ratio(statistics?.sharpeTStatistic), supportingValue: 'Registered evidence hurdle |t| > 3.0', minObservations: 20, insufficientReason: statistics?.available ? null : statistics?.reason, group: 'Statistical Confidence', priority: 96, tooltip: { measures: 'Per-period Sharpe multiplied by the square root of the sample count.', better: 'The registered multiple-testing hurdle is a positive t-statistic above 3.0.' } }, sample))
  standard.push(base({ id: 'sharpe_standard_error', name: 'Sharpe standard error', family: 'statistical_confidence', category: 'Statistical', value: statistics?.sharpeStandardErrorAnnual, formattedValue: statistics?.available ? `±${statistics.sharpeStandardErrorAnnual.toFixed(2)}` : 'Insufficient', minObservations: 20, insufficientReason: statistics?.available ? null : statistics?.reason, descriptive: true, group: 'Statistical Confidence', priority: 92, tooltip: { measures: 'Approximate annualized uncertainty around the naive Sharpe estimate.' } }, sample))
  const minTrack = statistics?.minTrackRecord
  standard.push(base({ id: 'minimum_track_record', name: 'Minimum track record length', family: 'statistical_confidence', category: 'Statistical', value: minTrack?.available ? minTrack.observations : null, formattedValue: minTrack?.available ? `${count(minTrack.observations)} returns` : 'Not estimable', minObservations: 20, insufficientReason: minTrack?.available ? null : minTrack?.reason || statistics?.reason, descriptive: true, group: 'Statistical Confidence', priority: 97, tooltip: TOOLTIP.mintrl }, sample))
  const dsr = statistics?.dsr
  standard.push(base({ id: 'dsr', name: 'Deflated Sharpe ratio', family: 'statistical_confidence', category: 'Statistical', value: dsr?.available ? dsr.value : null, formattedValue: dsr?.available ? percent(dsr.value * 100) : 'Insufficient', supportingValue: statistics?.trialCount ? `N=${statistics.trialCount} registered trials` : undefined, minObservations: 20, insufficientReason: dsr?.available ? null : dsr?.reason || statistics?.reason, group: 'Statistical Confidence', priority: 99, tooltip: TOOLTIP.dsr }, sample))
  standard.push(missing('Harvey–Liu haircut Sharpe', 'harvey_liu_haircut', 'statistical_confidence', 'Statistical', 'the cross-trial test-statistic distribution needed for the Harvey–Liu–Zhu multiple-testing haircut is not recorded', 'Statistical Confidence', 94, { measures: 'Sharpe after the Harvey–Liu–Zhu multiple-testing haircut.', better: 'The registered BHY evidence hurdle is t > 3.0; no haircut is fabricated without the trial distribution.' }))

  standard.push(base({ id: 'maximum_drawdown', name: 'Maximum drawdown', family: 'drawdown_severity', value: performanceValue('maxDrawdown'), formattedValue: percent(performanceValue('maxDrawdown')), minObservations: 20, insufficientReason: unavailable, group: 'Drawdown', priority: 100, tooltip: { measures: 'Worst peak-to-trough decline in the selected sample.', better: 'A smaller loss magnitude is generally preferable.' } }, sample))
  standard.push(base({ id: 'current_drawdown', name: 'Current drawdown', family: 'drawdown_severity', value: performanceValue('currentDrawdown'), formattedValue: percent(performanceValue('currentDrawdown')), minObservations: 20, insufficientReason: unavailable, group: 'Drawdown', priority: 80, tooltip: { measures: 'Current distance below the sample high-water mark.' } }, sample))
  standard.push(base({ id: 'longest_underwater', name: 'Longest underwater', family: 'drawdown_persistence', value: underwater?.available ? underwater.longestUnderwaterDays : null, formattedValue: underwater?.available ? duration(underwater.longestUnderwaterDays) : 'Insufficient', supportingValue: underwater?.available ? (underwater.stillUnderwater ? `Below its high since ${underwater.highWaterDate}` : `Recovered · at a high as of ${underwater.highWaterDate}`) : undefined, minObservations: 2, insufficientReason: underwater?.available ? null : underwater?.reason, group: 'Drawdown', priority: 78, tooltip: { measures: 'Longest wall-clock span below a prior high-water mark.' } }, sample))
  standard.push(base({ id: 'current_underwater', name: 'Current underwater duration', family: 'drawdown_persistence', value: underwater?.available ? underwater.currentUnderwaterDays : null, formattedValue: underwater?.available ? duration(underwater.currentUnderwaterDays) : 'Insufficient', minObservations: 2, insufficientReason: underwater?.available ? null : underwater?.reason, descriptive: true, group: 'Drawdown', priority: 54, tooltip: { measures: 'Wall-clock time since the current high-water mark, or zero when at a high.' } }, sample))
  standard.push(base({ id: 'deepest_drawdown', name: 'Deepest drawdown', family: 'drawdown_severity', value: underwater?.available ? underwater.deepestDrawdownPct : null, formattedValue: underwater?.available ? percent(underwater.deepestDrawdownPct) : 'Insufficient', minObservations: 2, insufficientReason: underwater?.available ? null : underwater?.reason, descriptive: true, group: 'Drawdown', priority: 48, tooltip: { measures: 'Deepest peak-to-trough decline, retained as the canonical duplicate of maximum drawdown.' } }, sample))
  standard.push(base({ id: 'recovery_deepest', name: 'Recovery time for deepest drawdown', family: 'drawdown_persistence', value: underwater?.available ? underwater.recoveryDaysForDeepest : null, formattedValue: duration(underwater?.recoveryDaysForDeepest), minObservations: 2, insufficientReason: underwater?.available && underwater.recoveryDaysForDeepest == null ? 'the deepest drawdown has not recovered yet' : underwater?.available ? null : underwater?.reason, descriptive: true, group: 'Drawdown', priority: 58, tooltip: { measures: 'Wall-clock time from the high preceding the deepest drawdown until recovery.' } }, sample))

  const moments = statistics?.moments
  const tail = statistics?.tail
  standard.push(base({ id: 'skewness', name: 'Skewness', family: 'tail_risk', category: 'Risk', value: moments?.available ? moments.skewness : null, formattedValue: ratio(moments?.skewness), minObservations: 20, insufficientReason: moments?.available ? null : moments?.reason || statistics?.reason, descriptive: true, group: 'Tail Risk', priority: 65, tooltip: { measures: 'Asymmetry of daily returns; negative skew places more mass in the left tail.' } }, sample))
  standard.push(base({ id: 'excess_kurtosis', name: 'Excess kurtosis', family: 'tail_risk', category: 'Risk', value: moments?.available ? moments.excessKurtosis : null, formattedValue: ratio(moments?.excessKurtosis), minObservations: 20, insufficientReason: moments?.available ? null : moments?.reason || statistics?.reason, descriptive: true, group: 'Tail Risk', priority: 64, tooltip: { measures: 'Tail weight relative to a normal distribution.' } }, sample))
  ;[['var_95', 'VaR 95%', 'var95Pct'], ['var_99', 'VaR 99%', 'var99Pct']].forEach(([id, name, key], index) => standard.push(base({ id, name, family: 'tail_risk', value: tail?.available ? tail[key] : null, formattedValue: tail?.available ? percent(tail[key]) : 'Insufficient', minObservations: 20, insufficientReason: tail?.available ? null : tail?.reason || statistics?.reason, group: 'Tail Risk', priority: 68 - index, tooltip: { measures: `Empirical one-day loss threshold at ${name.slice(-3)} confidence.` } }, sample)))
  ;[[95, 'expectedShortfall95Pct'], [97.5, 'expectedShortfall975Pct'], [99, 'expectedShortfall99Pct']].forEach(([level, key], index) => standard.push(base({ id: `expected_shortfall_${String(level).replace('.', '')}`, name: `Expected Shortfall ${level}%`, family: 'tail_risk', value: tail?.available ? tail[key] : null, formattedValue: tail?.available ? percent(tail[key]) : 'Insufficient', minObservations: 20, insufficientReason: tail?.available ? null : tail?.reason || statistics?.reason, group: 'Tail Risk', priority: 86 - index, tooltip: TOOLTIP.es }, sample)))
  ;[['omega', 'Omega ratio', 'omega', ratio], ['ulcer_index', 'Ulcer Index', 'ulcerIndexPct', percent], ['pain_index', 'Pain Index', 'painIndexPct', percent], ['pain_ratio', 'Pain Ratio', 'painRatio', ratio], ['tail_ratio', 'Tail ratio', 'tailRatio', ratio]].forEach(([id, name, key, formatter]) => standard.push(base({ id, name, family: 'tail_risk', value: tail?.available ? tail[key] : null, formattedValue: tail?.available ? formatter(tail[key]) : 'Insufficient', minObservations: 20, insufficientReason: tail?.available ? null : tail?.reason || statistics?.reason, group: 'Tail Risk', priority: 55, tooltip: { measures: name } }, sample)))
  ;[['worst_day', 'Worst day', 'worstDayPct'], ['worst_week', 'Worst week', 'worstWeekPct'], ['worst_month', 'Worst month', 'worstMonthPct']].forEach(([id, name, key]) => standard.push(base({ id, name, family: 'tail_risk', value: tail?.available ? tail[key] : null, formattedValue: tail?.available ? signedPercent(tail[key]) : 'Insufficient', minObservations: 20, insufficientReason: tail?.available ? null : tail?.reason || statistics?.reason, descriptive: true, group: 'Tail Risk', priority: 50, tooltip: { measures: `Worst observed ${name.slice(6).toLowerCase()} return in the selected sample.` } }, sample)))
  const drawdownDurations = tail?.available ? tail.drawdownEpisodes.map((row) => row.durationDays) : []
  const recoveryDurations = tail?.available ? tail.recoveredEpisodes.map((row) => row.recoveryDays) : []
  ;[
    ['median_drawdown_duration', 'Median drawdown duration', median(drawdownDurations)],
    ['maximum_drawdown_duration', 'Maximum drawdown duration', drawdownDurations.length ? Math.max(...drawdownDurations) : null],
    ['median_time_to_recovery', 'Median time to recovery', median(recoveryDurations)],
  ].forEach(([id, name, value]) => standard.push(base({ id, name, family: 'drawdown_persistence', category: 'Risk', value, formattedValue: duration(value), minObservations: 20, insufficientReason: finite(value) ? null : tail?.reason || 'at least one completed drawdown episode is required', descriptive: true, group: 'Drawdown', priority: 52, tooltip: { measures: name } }, sample)))
  standard.push(base({ id: 'autocorrelation_1', name: 'First-order autocorrelation', family: 'statistical_confidence', category: 'Statistical', value: statistics?.autocorrelation1, formattedValue: ratio(statistics?.autocorrelation1), minObservations: 20, insufficientReason: statistics?.available ? null : statistics?.reason, descriptive: true, group: 'Statistical Confidence', priority: 70, tooltip: { measures: 'Correlation of each daily excess return with the prior day.' } }, sample))
  standard.push(base({ id: 'ljung_box_q', name: 'Ljung–Box Q', family: 'statistical_confidence', category: 'Statistical', value: statistics?.ljungBox?.available ? statistics.ljungBox.value : null, formattedValue: ratio(statistics?.ljungBox?.value), minObservations: 20, insufficientReason: statistics?.ljungBox?.available ? null : statistics?.ljungBox?.reason || statistics?.reason, descriptive: true, group: 'Statistical Confidence', priority: 60, tooltip: { measures: 'Joint serial-correlation diagnostic across the displayed lags.' } }, sample))

  const comparison = []
  comparison.push(base({ id: 'information_ratio', name: 'Information ratio', family: 'relative_return', category: 'Benchmark', value: performanceValue('informationRatio'), formattedValue: ratio(performanceValue('informationRatio')), supportingValue: risk?.trackingErrorPct != null ? `${percent(risk.trackingErrorPct)} tracking error` : undefined, minObservations: 20, insufficientReason: performance?.available && performance.informationRatio == null ? performance.reason : unavailable, group: 'Relative Performance', priority: 95, tooltip: TOOLTIP.information }, sample))
  comparison.push(base({ id: 'acceleration', name: 'Acceleration', family: 'recent_change', category: 'Benchmark', value: acceleration?.available ? acceleration.acceleration : null, formattedValue: acceleration?.available ? `${acceleration.acceleration >= 0 ? '+' : '−'}${Math.abs(acceleration.acceleration).toFixed(2)}σ` : 'Insufficient', supportingValue: acceleration?.available ? `${accelerationLabel(acceleration)} · ${signedPercent(acceleration.recentExcessPct)} this quarter vs ${signedPercent(acceleration.priorExcessPct)} last, beta-adjusted` : undefined, minObservations: 2, insufficientReason: acceleration?.available ? null : acceleration?.reason, group: 'Relative Performance', priority: 62, tooltip: { measures: 'Change between recent and prior beta-adjusted excess-return windows.' } }, sample))
  comparison.push(base({ id: 'acceleration_pct', name: 'Acceleration percentage-point change', family: 'recent_change', category: 'Benchmark', value: acceleration?.available ? acceleration.accelerationPct : null, formattedValue: acceleration?.available ? signedPercent(acceleration.accelerationPct) : 'Insufficient', minObservations: 2, insufficientReason: acceleration?.available ? null : acceleration?.reason, descriptive: true, group: 'Relative Performance', priority: 44, tooltip: { measures: 'Recent beta-adjusted excess return less the prior comparable window, in percentage points.' } }, sample))
  comparison.push(base({ id: 'acceleration_beta', name: 'Acceleration fitted beta', family: 'recent_change', category: 'Benchmark', value: acceleration?.available ? acceleration.beta : null, formattedValue: acceleration?.available ? ratio(acceleration.beta) : 'Insufficient', minObservations: 2, insufficientReason: acceleration?.available ? null : acceleration?.reason, descriptive: true, group: 'Benchmark Fit', priority: 42, tooltip: { measures: 'Beta fitted on the two acceleration legs used to adjust benchmark return.' } }, sample))
  const captureObservations = capture?.available ? capture.observations.up + capture.observations.down : null
  comparison.push(base({ id: 'capture_profile', name: 'Capture profile', family: 'capture', category: 'Benchmark', value: capture?.available ? capture.captureSpread : null, formattedValue: capture?.available ? `${percent(capture.upCapturePct)} up · ${percent(capture.downCapturePct)} down` : 'Insufficient', supportingValue: capture?.available ? `Spread ${signedPercent(capture.captureSpread)}` : undefined, observations: captureObservations, minObservations: 16, insufficientReason: capture?.available ? null : capture?.reason, upCapture: capture?.upCapturePct, downCapture: capture?.downCapturePct, group: 'Capture Profile', priority: 94, tooltip: TOOLTIP.capture }, sample, { observations: captureObservations }))
  comparison.push(base({ id: 'up_capture', name: 'Up capture', family: 'capture', category: 'Benchmark', value: capture?.available ? capture.upCapturePct : null, formattedValue: capture?.available ? percent(capture.upCapturePct) : 'Insufficient', observations: captureObservations, minObservations: 16, insufficientReason: capture?.available ? null : capture?.reason, descriptive: true, group: 'Capture Profile', priority: 60, tooltip: TOOLTIP.capture }, sample, { observations: captureObservations }))
  comparison.push(base({ id: 'down_capture', name: 'Down capture', family: 'capture', category: 'Benchmark', value: capture?.available ? capture.downCapturePct : null, formattedValue: capture?.available ? percent(capture.downCapturePct) : 'Insufficient', observations: captureObservations, minObservations: 16, insufficientReason: capture?.available ? null : capture?.reason, descriptive: true, group: 'Capture Profile', priority: 60, tooltip: TOOLTIP.capture }, sample, { observations: captureObservations }))
  comparison.push(base({ id: 'capture_spread', name: 'Capture spread', family: 'capture', category: 'Benchmark', value: capture?.available ? capture.captureSpread : null, formattedValue: capture?.available ? signedPercent(capture.captureSpread) : 'Insufficient', supportingValue: capture?.available ? (capture.captureSpread >= 0 ? 'Keeping more of the upside than the downside' : 'Taking more of the downside than the upside') : undefined, observations: captureObservations, minObservations: 16, insufficientReason: capture?.available ? null : capture?.reason, group: 'Capture Profile', priority: 78, tooltip: TOOLTIP.capture }, sample, { observations: captureObservations }))
  const monthObservations = batting?.available ? batting.months : null
  const expectancy = batting?.available && finite(batting.averageWinPct) && finite(batting.averageLossPct)
    ? batting.wins / batting.months * batting.averageWinPct + batting.losses / batting.months * batting.averageLossPct
    : null
  comparison.push(base({ id: 'batting_average', name: 'Batting average', family: 'consistency', category: 'Benchmark', value: batting?.available ? batting.battingAveragePct : null, formattedValue: batting?.available ? percent(batting.battingAveragePct) : 'Insufficient', supportingValue: batting?.available ? `Beat the index in ${batting.wins} of ${batting.months} months${batting.winLossRatio ? ` · wins ${batting.winLossRatio.toFixed(1)}× the size of losses` : ''}` : undefined, minObservations: 6, insufficientReason: batting?.available ? null : batting?.reason, group: 'Consistency', priority: 82, tooltip: { measures: 'Share of calendar months in which the portfolio beat the benchmark.' } }, sample, { observations: monthObservations, frequency: 'monthly', startDate: batting?.firstMonth, endDate: batting?.lastMonth }))
  comparison.push(base({ id: 'relative_payoff', name: 'Relative payoff', family: 'consistency', category: 'Benchmark', value: batting?.available ? batting.winLossRatio : null, formattedValue: batting?.available ? `${ratio(batting.winLossRatio)}×` : 'Insufficient', minObservations: 6, insufficientReason: batting?.available ? null : batting?.reason, descriptive: true, group: 'Consistency', priority: 72, tooltip: { measures: 'Average benchmark-relative winning month divided by the magnitude of an average losing month.' } }, sample, { observations: monthObservations, frequency: 'monthly' }))
  comparison.push(base({ id: 'average_relative_win', name: 'Average winning-month excess', family: 'consistency', category: 'Benchmark', value: batting?.available ? batting.averageWinPct : null, formattedValue: batting?.available ? signedPercent(batting.averageWinPct) : 'Insufficient', minObservations: 6, insufficientReason: batting?.available ? null : batting?.reason, descriptive: true, group: 'Consistency', priority: 46, tooltip: { measures: 'Average benchmark-relative return in winning calendar months.' } }, sample, { observations: monthObservations, frequency: 'monthly' }))
  comparison.push(base({ id: 'average_relative_loss', name: 'Average losing-month excess', family: 'consistency', category: 'Benchmark', value: batting?.available ? batting.averageLossPct : null, formattedValue: batting?.available ? signedPercent(batting.averageLossPct) : 'Insufficient', minObservations: 6, insufficientReason: batting?.available ? null : batting?.reason, descriptive: true, group: 'Consistency', priority: 46, tooltip: { measures: 'Average benchmark-relative return in losing calendar months.' } }, sample, { observations: monthObservations, frequency: 'monthly' }))
  comparison.push(base({ id: 'relative_expectancy', name: 'Relative expectancy', family: 'consistency', category: 'Benchmark', value: expectancy, formattedValue: finite(expectancy) ? signedPercent(expectancy) : 'Insufficient', supportingValue: 'percentage points per month', minObservations: 6, insufficientReason: finite(expectancy) ? null : batting?.reason || 'average winning and losing month magnitudes are required', group: 'Consistency', priority: 88, tooltip: { measures: 'Win probability times average win plus loss probability times average loss.' } }, sample, { observations: monthObservations, frequency: 'monthly' }))

  if (factor?.available) {
    factor.models.forEach((model) => {
      if (!model.available) return
      comparison.push(base({ id: `${model.id}_alpha`, name: `${model.label} alpha`, family: 'factor_alpha', category: 'Benchmark', value: model.alphaAnnualPct, formattedValue: signedPercent(model.alphaAnnualPct), supportingValue: `HAC t ${ratio(model.alphaTStatistic)} · R² ${percent(model.rSquared * 100)}`, minObservations: 24, descriptive: true, group: 'Factor Attribution', priority: model.id === 'carhart4' ? 90 : 55, tooltip: TOOLTIP.alpha }, sample, { observations: model.observations, frequency: 'monthly', startDate: model.startMonth, endDate: model.endMonth }))
      comparison.push(base({ id: `${model.id}_alpha_t`, name: `${model.label} alpha t-statistic`, family: 'factor_alpha', category: 'Statistical', value: model.alphaTStatistic, formattedValue: ratio(model.alphaTStatistic), alphaAnnualPct: model.alphaAnnualPct, minObservations: 24, group: 'Factor Attribution', priority: model.id === 'carhart4' ? 96 : 56, tooltip: TOOLTIP.alpha }, sample, { observations: model.observations, frequency: 'monthly' }))
      Object.entries(model.loadings).forEach(([key, value]) => comparison.push(base({ id: `${model.id}_${key}_loading`, name: `${model.label} ${key.replace('_', ' ')} loading`, family: 'factor_alpha', category: 'Benchmark', value, formattedValue: ratio(value), supportingValue: `HAC SE ${ratio(model.standardErrors[key])}`, minObservations: 24, descriptive: true, group: 'Factor Attribution', priority: 30, tooltip: { measures: `Sensitivity to the ${key.replace('_', ' ')} factor in the ${model.label} regression.` } }, sample, { observations: model.observations, frequency: 'monthly' })))
      comparison.push(base({ id: `${model.id}_r_squared`, name: `${model.label} R²`, family: 'factor_alpha', category: 'Benchmark', value: model.rSquared * 100, formattedValue: percent(model.rSquared * 100), minObservations: 24, descriptive: true, group: 'Factor Attribution', priority: 35, tooltip: { measures: 'Share of sample return variance explained by the model factors.' } }, sample, { observations: model.observations, frequency: 'monthly' }))
    })
    const full = factor.models.at(-1)
    comparison.push(base({ id: 'residual_volatility', name: 'Residual volatility', family: 'factor_alpha', category: 'Risk', value: full.residualVolatilityAnnualPct, formattedValue: percent(full.residualVolatilityAnnualPct), minObservations: 24, descriptive: true, group: 'Factor Attribution', priority: 52, tooltip: { measures: 'Annualized volatility left unexplained by the full factor model.' } }, sample, { observations: full.observations, frequency: 'monthly' }))
    comparison.push(base({ id: 'unexplained_variance', name: 'Variance unexplained', family: 'factor_alpha', category: 'Risk', value: full.unexplainedVariancePct, formattedValue: percent(full.unexplainedVariancePct), minObservations: 24, descriptive: true, group: 'Factor Attribution', priority: 50, tooltip: { measures: 'Share of return variance not explained by the full factor model.' } }, sample, { observations: full.observations, frequency: 'monthly' }))
  } else {
    comparison.push(missing('Factor-adjusted alpha', 'factor_alpha', 'factor_alpha', 'Benchmark', factor?.reason || 'at least 24 overlapping monthly portfolio and factor observations are required', 'Factor Attribution', 96, TOOLTIP.alpha))
  }

  if (benchmark?.available) {
    benchmark.candidates.forEach((candidate) => {
      if (!candidate.available) {
        comparison.push(missing(`${candidate.label} benchmark fit`, `benchmark_${candidate.symbol?.toLowerCase()}_fit`, 'relative_return', 'Benchmark', candidate.reason, 'Benchmark Fit', 35))
        return
      }
      const support = `${candidate.observations} daily returns${benchmark.bestFit?.symbol === candidate.symbol ? ' · best fit' : ''}`
      ;[['beta', 'Beta', candidate.beta, ratio], ['correlation', 'Correlation', candidate.correlation, ratio], ['tracking_error', 'Tracking error (naive √252)', candidate.trackingErrorPct, percent], ['tracking_error_lo', 'Tracking error (Lo-adjusted)', candidate.loAdjustedTrackingErrorPct, percent], ['r_squared', 'R²', candidate.rSquared * 100, percent]].forEach(([suffix, label, value, formatter]) => comparison.push(base({ id: `${candidate.symbol.toLowerCase()}_${suffix}`, name: `${candidate.label} ${label}`, family: 'relative_return', category: 'Benchmark', value, formattedValue: formatter(value), supportingValue: support, minObservations: suffix === 'tracking_error_lo' ? 253 : 20, insufficientReason: suffix === 'tracking_error_lo' && !candidate.loTrackingFactor?.available ? candidate.loTrackingFactor?.reason : null, descriptive: true, group: 'Benchmark Fit', priority: benchmark.bestFit?.symbol === candidate.symbol ? 70 : 40, tooltip: suffix.startsWith('tracking_error') ? TOOLTIP.tracking : { measures: `${label} against ${candidate.label} on identical daily dates.` } }, sample, { observations: candidate.observations, startDate: candidate.startDate, endDate: candidate.endDate })))
    })
    comparison.push(missing('Sector-neutral benchmark fit', 'sector_neutral_fit', 'relative_return', 'Benchmark', benchmark.sectorNeutral.reason, 'Benchmark Fit', 32))
  } else comparison.push(missing('Best-fit benchmark', 'best_fit_benchmark', 'relative_return', 'Benchmark', 'daily candidate benchmark histories are required', 'Benchmark Fit', 80))

  const addBenchmarkComparison = (key, row, suffix) => {
    if (!row) return
    const label = `${row.label}${suffix}`
    comparison.push(base({ id: `${key}_information_ratio`, name: `${label} information ratio`, family: 'relative_return', category: 'Benchmark', value: row.performance?.available ? row.performance.informationRatio : null, formattedValue: row.performance?.available ? ratio(row.performance.informationRatio) : 'Insufficient', minObservations: 20, insufficientReason: row.performance?.available ? null : row.performance?.reason, group: 'Benchmark Fit', priority: key === 'best_fit' ? 74 : 58, tooltip: TOOLTIP.information }, sample))
    const observations = row.capture?.available ? row.capture.observations.up + row.capture.observations.down : null
    comparison.push(base({ id: `${key}_capture_profile`, name: `${label} capture profile`, family: 'capture', category: 'Benchmark', value: row.capture?.available ? row.capture.captureSpread : null, formattedValue: row.capture?.available ? `${percent(row.capture.upCapturePct)} up · ${percent(row.capture.downCapturePct)} down` : 'Insufficient', supportingValue: row.capture?.available ? `Spread ${signedPercent(row.capture.captureSpread)}` : undefined, upCapture: row.capture?.upCapturePct, downCapture: row.capture?.downCapturePct, minObservations: 16, insufficientReason: row.capture?.available ? null : row.capture?.reason, group: 'Benchmark Fit', priority: key === 'best_fit' ? 73 : 57, tooltip: TOOLTIP.capture }, sample, { observations }))
    comparison.push(base({ id: `${key}_batting_average`, name: `${label} batting average`, family: 'consistency', category: 'Benchmark', value: row.batting?.available ? row.batting.battingAveragePct : null, formattedValue: row.batting?.available ? percent(row.batting.battingAveragePct) : 'Insufficient', supportingValue: row.batting?.available ? `${row.batting.wins} / ${row.batting.months} months` : undefined, minObservations: 6, insufficientReason: row.batting?.available ? null : row.batting?.reason, group: 'Benchmark Fit', priority: key === 'best_fit' ? 72 : 56, tooltip: { measures: `Monthly benchmark-relative win rate against ${row.label}.` } }, sample, { observations: row.batting?.months, frequency: 'monthly' }))
  }
  addBenchmarkComparison('sp500', benchmarkComparisons?.spy, '')
  addBenchmarkComparison('best_fit', benchmarkComparisons?.best, benchmarkComparisons?.best?.symbol === 'SPY' ? ' (best fit and S&P 500)' : ' (best fit)')

  if (regime?.available) {
    ;[
      ['bull', 'Bull days'],
      ['bear', 'Bear days'],
      ['highVolatility', 'High-volatility days'],
      ['lowVolatility', 'Low-volatility days'],
    ].forEach(([key, label]) => {
      const row = regime[key]
      comparison.push(base({ id: `regime_${key}`, name: label, family: 'relative_return', category: 'Benchmark', value: row.meanDailyExcessPct, formattedValue: signedPercent(row.meanDailyExcessPct, 2), supportingValue: `${signedPercent(row.portfolioReturnPct)} portfolio · ${signedPercent(row.benchmarkReturnPct)} benchmark`, minObservations: 10, descriptive: true, group: 'Regime Performance', priority: 42, tooltip: { measures: `${label} performance under the displayed descriptive regime split.` } }, sample, { observations: row.observations }))
    })
  } else comparison.push(missing('Regime-conditional performance', 'regime_performance', 'relative_return', 'Benchmark', regime?.reason || 'daily portfolio and benchmark returns are required', 'Regime Performance', 45))

  const fast = []
  const window = (days) => shortTerm?.windows?.find((row) => row.days === days)
  ;[[7, 'Past week vs index'], [30, 'Past month vs index']].forEach(([days, name]) => {
    const item = window(days)
    const windowObservations = item?.observations ?? shortTerm?.baselineObservations ?? (item?.available ? 2 : 0)
    fast.push(base({ id: `recent_excess_${days}d`, name, family: 'recent_excess', category: 'Return', value: item?.available ? item.excessPct : null, formattedValue: item?.available ? signedPercent(item.excessPct) : 'Insufficient', supportingValue: item?.available ? `You ${signedPercent(item.portfolioPct)} · index ${signedPercent(item.benchmarkPct)}` : undefined, minObservations: 2, insufficientReason: item?.available ? null : item?.reason || shortTerm?.reason, rule: item?.available && finite(item.noiseFloorPct) ? { direction: 'high', positive: item.noiseFloorPct * 1.5, negative: -item.noiseFloorPct * 1.5, reason: 'recent excess return relative to its descriptive noise band' } : undefined, group: 'Recent Performance', priority: days === 30 ? 92 : 86, tooltip: { measures: `Portfolio return less benchmark return over the past ${days} calendar days.` } }, sample, { observations: windowObservations }))
    const noiseRatio = item?.available && finite(item.noiseFloorPct) && item.noiseFloorPct > 0 ? Math.abs(item.excessPct) / item.noiseFloorPct : null
    fast.push(base({ id: `signal_to_noise_${days}d`, name: `${days}-day signal to noise`, family: 'signal_noise', category: 'Statistical', value: noiseRatio, formattedValue: finite(noiseRatio) ? `${noiseRatio.toFixed(2)}×` : 'Insufficient', supportingValue: item?.available ? `${signedPercent(item.excessPct)} excess · ±${percent(item.noiseFloorPct)} floor` : undefined, excessReturn: item?.excessPct, minObservations: 2, insufficientReason: finite(noiseRatio) ? null : item?.reason || 'a measured excess return and noise floor are required', group: 'Signal Strength', priority: days === 30 ? 95 : 78, tooltip: { measures: 'Absolute excess return divided by its descriptive noise floor.', better: 'At least 1.5× is labelled meaningful; these bands are not formal significance levels.' } }, sample, { observations: windowObservations }))
  })
  const monthWindow = window(30)
  const weekWindow = window(7)
  const weekObservationsForDisplay = weekWindow?.observations ?? shortTerm?.baselineObservations ?? (weekWindow?.available ? 2 : 0)
  fast.push(base({ id: 'noise_floor_week', name: 'Noise floor (week)', family: 'signal_noise', category: 'Statistical', value: weekWindow?.available ? weekWindow.noiseFloorPct : null, formattedValue: weekWindow?.available && finite(weekWindow.noiseFloorPct) ? `±${percent(Math.abs(weekWindow.noiseFloorPct))}` : 'Insufficient', supportingValue: weekWindow?.available ? shortTermVerdict(weekWindow) : undefined, minObservations: 2, insufficientReason: weekWindow?.available ? null : weekWindow?.reason || 'a tracking-noise estimate is required', descriptive: true, group: 'Signal Strength', priority: 62, tooltip: { measures: 'One standard error of ordinary benchmark-relative movement over a week.' } }, sample, { observations: weekObservationsForDisplay }))
  const monthObservationsForDisplay = monthWindow?.observations ?? shortTerm?.baselineObservations ?? (monthWindow?.available ? 2 : 0)
  fast.push(base({ id: 'noise_floor_30d', name: 'Noise floor (month)', family: 'signal_noise', category: 'Statistical', value: monthWindow?.available ? monthWindow.noiseFloorPct : null, formattedValue: monthWindow?.available && finite(monthWindow.noiseFloorPct) ? `±${percent(Math.abs(monthWindow.noiseFloorPct))}` : 'Insufficient', supportingValue: monthWindow?.available ? shortTermVerdict(monthWindow) : undefined, minObservations: 2, insufficientReason: monthWindow?.available ? null : monthWindow?.reason || 'a tracking-noise estimate is required', descriptive: true, group: 'Signal Strength', priority: 84, tooltip: { measures: 'One standard error of the portfolio’s ordinary benchmark-relative movement over a month.' } }, sample, { observations: monthObservationsForDisplay }))
  const trackingObservations = shortTerm?.baselineObservations ?? (shortTerm?.available ? 20 : 0)
  fast.push(base({ id: 'tracking_risk', name: 'Recent tracking risk', family: 'relative_risk', category: 'Risk', value: shortTerm?.available ? shortTerm.recentTrackingRiskPct : null, formattedValue: shortTerm?.available ? percent(shortTerm.recentTrackingRiskPct) : 'Insufficient', supportingValue: finite(shortTerm?.baselineTrackingRiskPct) ? `${percent(shortTerm.baselineTrackingRiskPct)} baseline · naive √252` : undefined, baseline: shortTerm?.baselineTrackingRiskPct, minObservations: 20, insufficientReason: shortTerm?.available ? null : shortTerm?.reason, group: 'Risk Change', priority: 82, tooltip: TOOLTIP.tracking }, sample, { observations: trackingObservations }))
  fast.push(base({ id: 'baseline_tracking_risk', name: 'Baseline tracking risk', family: 'relative_risk', category: 'Risk', value: shortTerm?.available ? shortTerm.baselineTrackingRiskPct : null, formattedValue: shortTerm?.available ? percent(shortTerm.baselineTrackingRiskPct) : 'Insufficient', minObservations: 20, insufficientReason: shortTerm?.available ? null : shortTerm?.reason, descriptive: true, group: 'Risk Change', priority: 48, tooltip: TOOLTIP.tracking }, sample, { observations: trackingObservations }))
  fast.push(base({ id: 'short_term_beta', name: 'Fast-read fitted beta', family: 'relative_risk', category: 'Benchmark', value: shortTerm?.available ? shortTerm.beta : null, formattedValue: shortTerm?.available ? ratio(shortTerm.beta) : 'Insufficient', minObservations: 20, insufficientReason: shortTerm?.available && shortTerm.beta == null ? 'enough overlapping history is required to fit beta' : shortTerm?.available ? null : shortTerm?.reason, descriptive: true, group: 'Risk Change', priority: 46, tooltip: { measures: 'Beta fitted over the short-term view baseline and used for beta-adjusted excess returns.' } }, sample, { observations: trackingObservations }))
  fast.push(base({ id: 'active_share', name: 'Active share', family: 'portfolio_structure', category: 'Risk', value: risk?.activeSharePct, formattedValue: percent(risk?.activeSharePct), frequency: 'point', descriptive: true, missingInput: 'benchmark constituent weights are required', group: 'Portfolio Behavior', priority: 76, tooltip: TOOLTIP.activeShare }, sample, { observations: null, frequency: 'point' }))
  fast.push(base({ id: 'streak', name: 'Current streak', family: 'streak', category: 'Return', value: shortTerm?.available ? shortTerm.streak.observations : null, formattedValue: shortTerm?.available ? count(shortTerm.streak.observations) : 'Insufficient', supportingValue: shortTerm?.available ? `Periods ${shortTerm.streak.direction} of the index, spanning ${shortTerm.streak.days}d` : undefined, minObservations: 2, insufficientReason: shortTerm?.available ? null : shortTerm?.reason, descriptive: true, group: 'Portfolio Behavior', priority: 55, tooltip: { measures: 'Consecutive overlapping observations on the same side of the benchmark.' } }, sample, { observations: shortTerm?.available ? shortTerm.streak.observations : 0 }))

  const allMetrics = [...standard, ...comparison, ...fast]
  if (risk?.available) {
    allMetrics.push(base({ id: 'portfolio_volatility', name: 'Portfolio volatility', family: 'tail_risk', category: 'Risk', value: risk.portfolioVolatilityPct, formattedValue: percent(risk.portfolioVolatilityPct), minObservations: 20, descriptive: true, group: 'Exposure & Construction', priority: 58, tooltip: { measures: 'Annualized covariance-based volatility of current portfolio weights.' } }, sample, { observations: risk.observations }))
    allMetrics.push(base({ id: 'tracking_error_selected', name: 'Tracking error (selected benchmark)', family: 'relative_risk', category: 'Benchmark', value: risk.trackingErrorPct, formattedValue: percent(risk.trackingErrorPct), minObservations: 20, descriptive: true, missingInput: 'overlapping selected-benchmark returns are required', group: 'Benchmark Fit', priority: 58, tooltip: TOOLTIP.tracking }, sample, { observations: risk.observations }))
    ;(risk.contributions || []).forEach((row, index) => {
      allMetrics.push(metric({ id: index === 0 ? 'risk_contribution' : `risk_contribution_${row.ticker.toLowerCase()}`, name: `${row.ticker} share of total risk`, family: 'portfolio_structure', category: 'Risk', value: row.percentContributionToRisk, formattedValue: percent(row.percentContributionToRisk), supportingValue: `${percent(row.weightPct)} portfolio weight`, frequency: 'point', descriptive: true, group: 'Exposure & Construction', priority: index === 0 ? 52 : 25, tooltip: { measures: 'Euler component contribution as a share of total portfolio volatility.' } }))
      allMetrics.push(metric({ id: index === 0 ? 'marginal_risk_contribution' : `marginal_risk_contribution_${row.ticker.toLowerCase()}`, name: `${row.ticker} marginal risk contribution`, family: 'portfolio_structure', category: 'Risk', value: row.marginalContributionToRiskPct, formattedValue: percent(row.marginalContributionToRiskPct), frequency: 'point', descriptive: true, group: 'Exposure & Construction', priority: 20, tooltip: { measures: 'Marginal portfolio volatility change associated with the holding’s weight.' } }))
      allMetrics.push(metric({ id: index === 0 ? 'standalone_volatility' : `standalone_volatility_${row.ticker.toLowerCase()}`, name: `${row.ticker} standalone volatility`, family: 'portfolio_structure', category: 'Risk', value: row.standaloneVolatilityPct, formattedValue: percent(row.standaloneVolatilityPct), frequency: 'point', descriptive: true, group: 'Exposure & Construction', priority: 20, tooltip: { measures: 'Annualized volatility of the holding before portfolio correlations.' } }))
    })
  }
  allMetrics.push(metric({ id: 'portfolio_score', name: 'Portfolio Score (legacy)', family: 'portfolio_structure', category: 'Risk', value: legacyPortfolioScore?.available ? legacyPortfolioScore.score : null, formattedValue: legacyPortfolioScore?.available ? `${count(legacyPortfolioScore.score)} / 100` : 'Insufficient', supportingValue: 'Preserved in All Metrics; not used as the strategy evidence read', frequency: 'point', descriptive: true, insufficientReason: legacyPortfolioScore?.available ? null : legacyPortfolioScore?.reason || 'at least three measured portfolio components are required', group: 'Exposure & Construction', priority: 25, tooltip: { measures: 'Legacy weighted portfolio composite retained for metric preservation. The Overview uses auditable evidence counts, not this score.' } }))
  if (exposure?.available) {
    ;[['gross_exposure', 'Gross exposure', 'grossExposurePct', percent], ['net_exposure', 'Net exposure', 'netExposurePct', percent], ['leverage', 'Leverage', 'leverage', (value) => `${ratio(value)}×`], ['long_exposure', 'Long exposure', 'longExposurePct', percent], ['short_exposure', 'Short exposure', 'shortExposurePct', percent], ['position_count', 'Position count', 'positionCount', count], ['max_position_weight', 'Maximum position weight', 'maxPositionWeightPct', percent], ['hhi', 'Herfindahl concentration', 'hhi', (value) => Number(value).toFixed(3)], ['effective_positions', 'Effective positions', 'effectivePositions', ratio]].forEach(([id, name, key, formatter]) => allMetrics.push(metric({ id, name, family: 'portfolio_structure', category: 'Risk', value: exposure[key], formattedValue: formatter(exposure[key]), frequency: 'point', descriptive: !['effective_positions'].includes(id), constraintViolation: id === 'effective_positions' && exposure[key] < 5, group: 'Exposure & Construction', priority: id === 'effective_positions' ? 82 : 45, tooltip: { measures: name } })))
    allMetrics.push(missing('Sector tilts', 'sector_tilts', 'portfolio_structure', 'Benchmark', exposure.sectorTilts.reason, 'Exposure & Construction', 48))
    allMetrics.push(missing('ADV participation distribution', 'adv_participation', 'execution', 'Execution', exposure.advParticipation.reason, 'Exposure & Construction', 70))
  }

  const executionReason = execution?.reason || 'position-level trade or rebalance data is required'
  if (execution?.available) {
    allMetrics.push(metric({ id: 'one_way_turnover', name: 'One-way turnover', family: 'execution', category: 'Execution', value: execution.annualOneWayTurnover, formattedValue: finite(execution.annualOneWayTurnover) ? `${ratio(execution.annualOneWayTurnover)}× / year` : 'Insufficient', frequency: 'point', descriptive: true, missingInput: 'dated rebalances spanning more than one date are required for annual turnover', group: 'Cost & Capacity', priority: 88, tooltip: TOOLTIP.turnover }))
    allMetrics.push(metric({ id: 'two_way_turnover', name: 'Two-way turnover', family: 'execution', category: 'Execution', value: execution.twoWayTurnover, formattedValue: `${ratio(execution.twoWayTurnover)}×`, frequency: 'point', descriptive: true, group: 'Cost & Capacity', priority: 76, tooltip: TOOLTIP.turnover }))
    allMetrics.push(metric({ id: 'average_holding_period', name: 'Average holding period', family: 'execution', category: 'Execution', value: execution.averageHoldingPeriodYears, formattedValue: finite(execution.averageHoldingPeriodYears) ? `${ratio(execution.averageHoldingPeriodYears)} years` : 'Insufficient', frequency: 'point', descriptive: true, missingInput: 'annualized one-way turnover is required', group: 'Cost & Capacity', priority: 72, tooltip: { measures: 'Reciprocal of annual one-way turnover, reported as an approximation.' } }))
    allMetrics.push(metric({ id: 'break_even_cost', name: 'Break-even cost per trade', family: 'execution', category: 'Cost', value: execution.breakEvenCostBps, formattedValue: finite(execution.breakEvenCostBps) ? `${ratio(execution.breakEvenCostBps)} bps` : 'Insufficient', frequency: 'point', missingInput: 'positive gross excess return and two-way turnover are required', group: 'Cost & Capacity', priority: 100, tooltip: TOOLTIP.breakEven }))
  } else {
    ;[['one_way_turnover', 'One-way turnover', TOOLTIP.turnover], ['two_way_turnover', 'Two-way turnover', TOOLTIP.turnover], ['average_holding_period', 'Average holding period'], ['gross_return', 'Gross return'], ['net_return', 'Net return'], ['net_sharpe', 'Net Sharpe'], ['break_even_cost', 'Break-even cost per trade', TOOLTIP.breakEven], ['cost_drag', 'Cost drag'], ['capacity_1d', 'Capacity at 1-day horizon'], ['capacity_5d', 'Capacity at 5-day horizon']].forEach(([id, name, tooltip]) => allMetrics.push(missing(name, id, 'execution', id.includes('cost') || id.includes('capacity') ? 'Cost' : 'Execution', executionReason, 'Cost & Capacity', id === 'break_even_cost' ? 100 : 60, tooltip)))
  }

  const robust = robustness || {}
  ;[['walk_forward_efficiency', 'Walk-forward efficiency', robust.walkForwardEfficiency, TOOLTIP.wfe], ['pbo', 'Probability of backtest overfitting', robust.pbo, TOOLTIP.pbo], ['cpcv', 'Combinatorial purged CV', robust.cpcv], ['parameter_sensitivity', 'Parameter sensitivity', robust.parameterSensitivity]].forEach(([id, name, row, tooltip]) => {
    allMetrics.push(metric({ id, name, family: 'statistical_confidence', category: id === 'pbo' ? 'Statistical' : 'Algorithm', value: row?.available && finite(row.value) ? row.value : null, formattedValue: row?.available && finite(row.value) ? (id === 'pbo' ? percent(row.value * 100) : ratio(row.value)) : 'Insufficient', frequency: 'point', descriptive: id !== 'pbo', insufficientReason: row?.available ? null : row?.reason || 'registered validation output is required', group: 'Robustness & Validation', priority: 80, tooltip: tooltip || { measures: name } }))
  })

  return {
    standard,
    comparison,
    fast,
    all: allMetrics,
    groups: [...new Set(allMetrics.map((row) => row.group))].map((name) => ({ name, metrics: allMetrics.filter((row) => row.group === name) })),
  }
}
