"""Value sleeve (docs/RESEARCH-CONTRACT.md, brief section 6.1).

Worked example for the sleeve interface (pipeline/sleeves/__init__.py) -- wraps the existing
valuation scoring in scorer.py rather than reimplementing it. scorer._band_valuation_score
computes all six fundamental categories (valuation, profitability, financial_health, growth,
capital_allocation, accounting_quality) in one pass for efficiency; this sleeve isolates just
the valuation category and its own metrics, because a value sleeve blended with profitability
would no longer be independently testable against a value-specific target.

Value-family metric membership comes from pipeline/config/feature_registry.json (generated by
build_feature_registry.py), not a second hardcoded list here.
"""

from common import load_json
from scorer import SETTINGS, valuation_score
from sleeves import empty_sleeve, ineligible_sleeve

VERSION = "1.0.0"
TARGET_HORIZON_DAYS = 63  # matches the research contract's primary target horizon


def _value_metric_ids():
    registry = load_json("feature_registry.json", from_config=True) or {}
    return sorted(
        feature_id for feature_id, entry in registry.get("features", {}).items()
        if entry.get("family") == "value"
    )


def score_value_sleeve(snapshot, as_of=None):
    """Score one company's value sleeve from its already-fetched snapshot.

    ``snapshot`` is the same dict advisor_engine.build_research receives -- this does not
    fetch anything new, only reshapes what scorer.py already computes into the sleeve
    contract.
    """
    if snapshot.get("is_etf"):
        return ineligible_sleeve("value", VERSION, TARGET_HORIZON_DAYS, ["unsupported_security_type"])

    score, detail = valuation_score(snapshot)
    metric_ids = _value_metric_ids()
    result = empty_sleeve("value", VERSION, TARGET_HORIZON_DAYS, as_of)

    if score is None:
        result["eligibility"] = {"eligible": False, "reasons": ["missing_provider_data"]}
        result["warnings"].append("No fundamental category resolved for this snapshot.")
        return result

    raw_features = {metric_id: snapshot.get(metric_id) for metric_id in metric_ids}
    # sales_multiple has no snapshot field of its own -- scorer.sales_multiple_score picks
    # whichever of ev_to_sales/price_to_sales the company actually has (detail records which
    # one via sales_multiple_basis) and scores that. Report the value that was actually used.
    sales_basis = detail.get("sales_multiple_basis")
    if "sales_multiple" in raw_features and sales_basis:
        raw_features["sales_multiple"] = snapshot.get(sales_basis)
    normalized_features = {metric_id: detail.get(metric_id) for metric_id in metric_ids}
    resolved = sum(1 for value in raw_features.values() if value is not None)

    result["raw_features"] = raw_features
    result["normalized_features"] = normalized_features
    result["subscores"] = {"valuation": detail.get("categories", {}).get("valuation")}
    result["raw_score"] = detail.get("categories", {}).get("valuation")
    # Sleeve-local confidence: fraction of this sleeve's own metrics that resolved, not the
    # whole-company fundamental coverage (which mixes in profitability/growth/etc. metrics
    # this sleeve doesn't use) -- see pipeline/confidence.py for the company-level analog.
    result["confidence"] = round(resolved / len(metric_ids), 2) if metric_ids else None
    if resolved == 0:
        result["eligibility"] = {"eligible": False, "reasons": ["missing_provider_data"]}
    elif resolved < len(metric_ids) // 2:
        result["warnings"].append(
            f"Only {resolved}/{len(metric_ids)} value metrics resolved for this company."
        )
    negative_denominator_flags = [
        metric_id for metric_id in ("ev_to_ebitda", "ev_to_ebit", "ev_to_fcf")
        if raw_features.get(metric_id) is not None and raw_features[metric_id] <= 0
    ]
    if negative_denominator_flags:
        result["warnings"].append(
            f"Non-positive denominator excluded from scoring: {', '.join(negative_denominator_flags)}"
        )
    result["explanation"] = [
        f"{metric_id}: raw={raw_features[metric_id]}, normalized={normalized_features[metric_id]}"
        for metric_id in metric_ids
        if raw_features.get(metric_id) is not None
    ]
    return result
