"""Value sleeve (docs/RESEARCH-CONTRACT.md, brief section 6.1).

Wraps scorer.py's existing "valuation" fundamental category rather than reimplementing it.
Value-family metric membership comes from pipeline/config/feature_registry.json (generated by
build_feature_registry.py), not a hardcoded list here.
"""

from sleeves._fundamentals import score_fundamentals_family_sleeve

VERSION = "1.0.0"
TARGET_HORIZON_DAYS = 63  # matches the research contract's primary target horizon


def score_value_sleeve(snapshot, as_of=None):
    """Score one company's value sleeve from its already-fetched snapshot.

    ``snapshot`` is the same dict advisor_engine.build_research receives -- this does not
    fetch anything new, only reshapes what scorer.py already computes into the sleeve
    contract.
    """
    return score_fundamentals_family_sleeve(
        "value", "value", ("valuation",), VERSION, TARGET_HORIZON_DAYS, snapshot, as_of,
    )
